/*
 * gcode.h
 *
 *  Created on: 16 Sep 2016
 *      Author: Alex
 */

#ifndef INC_GCODE_H_
#define INC_GCODE_H_

#include <stdint.h>

enum
{
	GCODE_MOVEMENT_RAPID 		= 0,
	GCODE_MOVEMENT_CONTROLLED 	= 1,
	GCODE_WAIT					= 4,
	GCODE_SET_UNITS_INCH		= 20,
	GCODE_SET_UNITS_MM			= 21,
	GCODE_HOME					= 28,
	GCODE_POSITIONING_ABSOLUTE	= 90,
	GCODE_POSITIONING_RELATIVE	= 91,
	GCODE_SET_POSITION			= 92,
}GCODE_general;

enum
{
	GCODE_STOP_WHEN_READY		= 0,	// stop when buffer is empty
	GCODE_MOTORS_ENABLE			= 17,
	GCODE_MOTORS_DISABLE		= 18,

	GCODE_FILESYSTEM_MOUNT		= 21,
	GCODE_FILESYSTEM_UNMOUNT	= 22,

	GCODE_PRINT_PAUSE			= 25,

	GCODE_PRINT_EJECT			= 40,

	GCODE_FAN_SET_SPEED			= 106,
	GCODE_FAN_OFF				= 107,


	GCODE_SET_DEBUG_LEVEL		= 111,
	GCODE_STOP_EMERGENCY		= 112,

	GCODE_GET_CURRENT_POSITION	= 114,

	GCODE_EXTRUDER_VALVE_OPEN	= 126,
	GCODE_EXTRUDER_VALVE_CLOSE	= 127,
	GCODE_EXTRUDER_PRESSURE_SET	= 128,
	GCODE_EXTRUDE_PRESSURE_OFF 	= 129,
	GCODE_HEATED_BED_SET_TEMPERATURE	= 140,
	GCODE_HEATED_CHAMBER_SET_TEMPERATURE	= 141,
}GCODE_machine;

typedef struct
{
	char 	type;		// 'G' or 'M' code
	uint8_t	number;		// command number
}GCODE;



#endif /* INC_GCODE_H_ */
